git rm     app/views/admin/index.html.erb
	git rm     app/views/carts/_form.html.erb
	git rm     app/views/carts/edit.html.erb
	git rm     app/views/carts/index.html.erb
	git rm     app/views/carts/new.html.erb
	git rm     app/views/carts/show.html.erb
	git rm     app/views/layouts/application.html.erb
	git rm     app/views/layouts/mailer.html.erb
	git rm     app/views/layouts/mailer.text.erb
	git rm     app/views/line_items/_form.html.erb
	git rm     app/views/line_items/_line_item.html.erb
	git rm     app/views/line_items/_line_item.text.erb
	git rm     app/views/line_items/create.js.erb
	git rm     app/views/line_items/edit.html.erb
	git rm     app/views/line_items/index.html.erb
	git rm     app/views/line_items/new.html.erb
	git rm     app/views/line_items/show.html.erb
	git rm     app/views/order_notifier/received.html.erb
	git rm     app/views/order_notifier/received.text.erb
	git rm     app/views/order_notifier/shipped.html.erb
	git rm     app/views/order_notifier/shipped.text.erb
	git rm     app/views/orders/_form.html.erb
	git rm     app/views/orders/edit.html.erb
	git rm     app/views/orders/index.html.erb
	git rm     app/views/orders/new.html.erb
	git rm     app/views/orders/show.html.erb
	git rm     app/views/products/_form.html.erb
	git rm     app/views/products/edit.html.erb
	git rm     app/views/products/index.html.erb
	git rm     app/views/products/new.html.erb
	git rm     app/views/products/show.html.erb
	git rm     app/views/sessions/create.html.erb
	git rm     app/views/sessions/destroy.html.erb
	git rm     app/views/sessions/new.html.erb
	git rm     app/views/store/index.html.erb
	git rm     app/views/users/_form.html.erb
	git rm     app/views/users/edit.html.erb
	git rm     app/views/users/index.html.erb
	git rm     app/views/users/new.html.erb
	git rm     app/views/users/show.html.erb
