default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: zues
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: depot

test:
  <<: *default
  database: depot 

production:
  <<: *default
  database: depot
